language: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  # install Lua
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

  # install optional deps
  - luarocks show lpeg || luarocks install lpeg

install:
  - luarocks make rockspecs/lua-websockets-extensions-scm-0.rockspec

before_script:
  - luarocks show lunitx           || luarocks install lunitx
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls

script: 
  - cd test
  - lunit.sh test_extensions.lua
  
after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
